services:
  frontend:
    build:
      context: ./dev
      dockerfile: node_java.Dockerfile
    working_dir: /usr/local/frontend
    ports:
      - 9630:9630
    volumes:
      - ./frontend:/usr/local/frontend
      - maven:/root/.m2
      - node_modules:/usr/local/node_modules
    command: yarn dev

  ssr:
    image: denoland/deno:2.1.9
    volumes:
      - ./render:/usr/local/render
    working_dir: /usr/local/render
    command: |
      bash -c '
        until deno run --reload --allow-net --allow-import serve.tsx; do
          echo "Deno died, retrying..."
          sleep 5
        done
      '

  gateway:
    volumes:
      - ./dev/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 3000:3000
    networks:
      default:
        aliases:
          # setting this so it has the same hostname both
          # in the docker virtual network and from the
          # host's point of view as well
          - hoge.lvh.me
    image: nginx:1.27.4-alpine

volumes:
  maven:
  shadow_maven:
  node_modules:
