version: '3'
services:
  browser:
    image: ichimai_frontend
    working_dir: /usr/local/browser
    ports:
      - 9630:9630
    volumes:
      - ./browser:/usr/local/browser
      - maven:/root/.m2
      - node_modules:/usr/local/node_modules
    command: yarn dev

  ssr:
    image: denoland/deno:1.26.1
    ports:
      - 3050:3050
    volumes:
      - ./render:/usr/local/render
    working_dir: /usr/local/render
    command: deno run --reload --allow-net serve.tsx

volumes:
  maven:
  shadow_maven:
  node_modules:
